"""initial schema

Revision ID: a155b5ee8b72
Revises: 
Create Date: 2026-06-15 17:19:56.733935

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import pgvector.sqlalchemy
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a155b5ee8b72'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Required extensions: PostGIS (geometry) and pgvector (embeddings).
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('tourists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.Column('emergency_contact', sa.String(length=64), nullable=True),
    sa.Column('planned_route', Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_purpose', sa.Enum('SAFETY_MONITORING', 'EMERGENCY_RESPONSE', 'ANALYTICS', name='consentpurpose'), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_ref')
    )
    op.create_geospatial_table('zones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_category', sa.Enum('LOW', 'MODERATE', 'HIGH', 'RESTRICTED', name='riskcategory'), nullable=False),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_zones_geom', 'zones', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tourist_id', sa.Uuid(), nullable=True),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('incident_type', sa.Enum('GEOFENCE_BREACH', 'ROUTE_DEVIATION', 'INACTIVITY', 'CROWD_DENSITY', 'PANIC', 'OTHER', name='incidenttype'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED', name='incidentstatus'), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tourist_id'], ['tourists.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_incidents_geom', 'incidents', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('location_pings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tourist_id', sa.Uuid(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['tourist_id'], ['tourists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_location_pings_geom', 'location_pings', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_pings_tourist_recorded', 'location_pings', ['tourist_id', 'recorded_at'], unique=False)
    op.create_geospatial_table('risk_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('CRIME', 'NATURAL_HAZARD', 'CIVIL_UNREST', 'ACCIDENT', 'HEALTH', 'ADVISORY', 'OTHER', name='riskeventtype'), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=256), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_confidence_unit'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_risk_events_geom', 'risk_events', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'ACKNOWLEDGED', 'CLOSED', name='alertstatus'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_geospatial_index('idx_risk_events_geom', table_name='risk_events', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('risk_events')
    op.drop_index('ix_pings_tourist_recorded', table_name='location_pings')
    op.drop_geospatial_index('idx_location_pings_geom', table_name='location_pings', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('location_pings')
    op.drop_geospatial_index('idx_incidents_geom', table_name='incidents', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('incidents')
    op.drop_geospatial_index('idx_zones_geom', table_name='zones', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('zones')
    op.drop_geospatial_table('tourists')
    # ### end Alembic commands ###
    # Enum types are not dropped by drop_table; remove them so a re-upgrade
    # can recreate them cleanly.
    for enum_name in (
        "consentpurpose",
        "riskcategory",
        "incidenttype",
        "incidentstatus",
        "riskeventtype",
        "alertseverity",
        "alertstatus",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
